### ISSUE TITLE
Epic Games Launcher support?

### ISSUE THREAD

**Issue by ManikandanGuru** [automuteus/amonguscapture#121]
Hi,
I know this only works with Steam launcher. But I don't know where I can ask about the Epic games launcher support here in GitHub. Would it come anytime sooner?
Thanks.

**Comment by ManikandanGuru** [comment]
When I use it from Epic Games launcher it just gives still looking for modules... error all the time.

**Comment by CarbonNeuron** [comment]
Have you tried launching the capture after the game has loaded?

**Comment by ManikandanGuru** [comment]
Yes, I did. I even purchased it in Steam just to check this and yeah it worked when I launched it from the Steam store and mute and defean also worked perfectly fine with the Steam version.

With Epic Games it just shows still looking for modules... error all the time.

**Comment by CarbonNeuron** [comment]
@varedz worked on epic games support.

**Comment by varedz** [comment]
@CarbonNeuron The pointers look to be fine, I think it may be ProcessMemory

**Comment by varedz** [comment]
Seems Client Verification never goes through

**Comment by varedz** [comment]
@CarbonNeuron Uh.. Seems the offsets are completely different aswell..

**Comment by varedz** [comment]
@ManikandanGuru Thanks for letting us know, we've found the issues, it will take some time to fix it all but we'll give you updates.

**Comment by ManikandanGuru** [comment]
Awesome. Thanks for the quick update @varedz. Now I can go for a refund in Steam and keep my Epic Game. LOL 😂

**Comment by CarbonNeuron** [comment]
Just a bump that this is being worked on. A major component was added in e4ba6108be6f0280ccb688aba06e13a7da5df021.

**Comment by varedz** [comment]
Made decent progress on the new offsets aswell.

**Comment by mtaku3** [comment]
Hey guys! I made a clone of AmongUsCapture which support Epic Games' versions 😄
Please check and try [this](https://github.com/mtaku3/AmongUsCapture)
Usage is same as original one 👍

**Comment by CarbonNeuron** [comment]
> 
> 
> Hey guys! I made a clone of AmongUsCapture which support Epic Games' versions 😄
> Please check and try [this](https://github.com/mtaku3/AmongUsCapture)
> Usage is same as original one 👍

Hey that is great. If you made a fork it would be way more easier to see your changes and add them to capture. But as it stands now, I really can't do anything with this lol

**Comment by mtaku3** [comment]
Thanks for reply 😀
I'm glad that I could hear your opinion.
I forgot to make it as fork repository, so I made it right now.
The most of the part is same as your original logic but the meetinghud is the hardest part for me cause I'm the beginner about memory 🤣
It was good changes that you changed offsets.json configuration to use array for some offsets.
So I think I can use same logic as yours in future update.
I'll join your discord to check yours out too 😉
Thank you

**Comment by CarbonNeuron** [comment]
> 
> 
> Thanks for reply 😀
> I'm glad that I could hear your opinion.
> I forgot to make it as fork repository, so I made it right now.
> The most of the part is same as your original logic but the meetinghud is the hardest part for me cause I'm the beginner about memory 🤣
> It was good changes that you changed offsets.json configuration to use array for some offsets.
> So I think I can use same logic as yours in future update.
> I'll join your discord to check yours out too 😉
> Thank you

Well it looks like the PlayerInfo object field offsets changed, so we will probably need to restructure how stuff works even more.

**Comment by CarbonNeuron** [comment]
> 
> 
> Thanks for reply 😀
> I'm glad that I could hear your opinion.
> I forgot to make it as fork repository, so I made it right now.
> The most of the part is same as your original logic but the meetinghud is the hardest part for me cause I'm the beginner about memory 🤣
> It was good changes that you changed offsets.json configuration to use array for some offsets.
> So I think I can use same logic as yours in future update.
> I'll join your discord to check yours out too 😉
> Thank you

I forgot that we need to add the discord to our readme. Its [here](https://discord.com/invite/ZkqZSWF)

**Comment by mtaku3** [comment]
Thanks for discord invitation
And I changed GetString function in ProcessMemory
You should check it too

**Comment by CarbonNeuron** [comment]
Added in d1cc4ef983c2d63cdc90296722c91b9f5026af21

**Comment by CarbonNeuron** [comment]
@all-contributors please add @mtaku3 for research

**Comment by CarbonNeuron** [comment]
@all-contributors add @mtaku3 research

**Comment by CarbonNeuron** [comment]
@all-contributors add @mtaku3 data collection
