### ISSUE TITLE
AmongUsCapture crashing

### ISSUE THREAD

**Issue by Yng-Ducky09** [automuteus/amonguscapture#131]
Every time I open the AmongUsCapture it crashes.

**Comment by Yng-Ducky09** [comment]
And I noticed it only crashes when I have Among Us open.

**Comment by CarbonNeuron** [comment]
Can you give logs in the %appdata%/AmongUsCapture/Logs folder?

**Comment by Yng-Ducky09** [comment]
Capture version: 2.8.8.0

03:41:22.5741 | DISCORDHANDLER | Trying to connect to discord
03:41:22.6949 | DISCORD.NET | 22:41:22 Discord     Discord.Net v2.2.0 (API v6)
03:41:24.0903 | DISCORD.NET | 22:41:24 Gateway     Connecting
03:41:26.6114 | DISCORD.NET | 22:41:26 Gateway     Connected
03:41:27.1126 | DISCORD.NET | Connection successful! ID: 799836316774563891, name: Among Us Bot
03:41:27.1280 | DISCORD.NET | 22:41:27 Gateway     Ready
03:42:12.9383 | DISCORD.NET | Disconnecting from discord
03:42:12.9484 | WARNING | This MAY cause undesired behaviour if already connected to a server.
03:42:12.9661 | DISCORDHANDLER | Trying to connect to discord
03:42:12.9767 | DISCORD.NET | 22:42:12 Discord     Discord.Net v2.2.0 (API v6)
03:42:14.4105 | DISCORD.NET | 22:42:14 Gateway     Connecting
03:42:16.2361 | DISCORD.NET | 22:42:16 Gateway     Connected
03:42:16.7390 | DISCORD.NET | Connection successful! ID: 799836316774563891, name: Among Us Bot
03:42:16.7528 | DISCORD.NET | 22:42:16 Gateway     Ready
03:44:04.8213 | DISCORD.NET | Disconnecting from discord
03:44:04.8213 | WARNING | This MAY cause undesired behaviour if already connected to a server.
03:44:04.8460 | DISCORDHANDLER | Trying to connect to discord
03:44:04.8564 | DISCORD.NET | 22:44:04 Discord     Discord.Net v2.2.0 (API v6)
03:44:08.8847 | DISCORD.NET | 22:44:08 Gateway     Connecting
03:44:10.1536 | DISCORD.NET | 22:44:10 Gateway     Connected
03:44:10.6545 | DISCORD.NET | Connection successful! ID: 799836316774563891, name: Among Us Bot
03:44:10.6545 | DISCORD.NET | 22:44:10 Gateway     Ready
03:45:11.6239 | DISCORD.NET | 22:45:11 Gateway     Left Robo Rob

Capture version: 2.8.8.0

**Comment by CarbonNeuron** [comment]
Try deleting the AmongUsCapture folder and reopening. That may fix it.

**Comment by CarbonNeuron** [comment]
Has this been fixed?

**Comment by Yng-Ducky09** [comment]
yes thank you
