### ISSUE TITLE
Install batch file crash

### ISSUE THREAD

**Issue by WarrenSchultz** [automuteus/amonguscapture#135]
This error pops up after downloading the redist update, and before the redist installer actually started running.
(Note, I already have the redist installed.)

![image](https://user-images.githubusercontent.com/8450968/104977486-a79a3100-59cd-11eb-8d9c-e7189499edd7.png)

**Comment by Wolfhound905** [comment]
Do you still have the batch file? If so can you please send it here? This was caused by an incorrect link in the batch when I was moving branches.

**Comment by Wolfhound905** [comment]
If you can try this again with the newest version [here](https://github.com/automuteus/capture-install) that would be appreciated, I do believe I fixed this error.

**Comment by WarrenSchultz** [comment]
Sorry, I was busy and missed your original request. Here's the previous batch, I'll try the new one.

[CaptureInstaller.zip](https://github.com/automuteus/amonguscapture/files/5843581/CaptureInstaller.zip)

**Comment by WarrenSchultz** [comment]
Yup, new version worked. I ran the bot, it requested an update, ran it, and it worked. Great job, thanks!

**Comment by CarbonNeuron** [comment]
Oops sorry for the double close. Make sure to close issues in the future when your problem is resolved. 

Happy auto muting.
