### ISSUE TITLE
Capture thinks Game is outdated

### ISSUE THREAD

**Issue by HandyHat** [automuteus/amonguscapture#152]
[] Upload logs (If applicable, Can be found in Settings>Debug>Open logs folder> Latest.log)

Capture version: 3.1.6.0

```
17:09:00.0384|INFO|AmongUsCapture.GameMemReader|Connected to Among Us process (17124)
17:09:00.2732|INFO|AmongUsCapture.GameMemReader|Client verification: "PASS"
17:09:00.5657|INFO|AmongUsCapture.GameMemReader|GameAssembly sha256: "B718DBA116D77D3B2359BD36A33995D608608FD2562C5B0B23755023FB7583D6"
17:09:00.5718|FATAL|AmongUsCapture.GameMemReader|No offsets found for hash: "B718DBA116D77D3B2359BD36A33995D608608FD2562C5B0B23755023FB7583D6"
17:09:00.5718|ERROR|AmongUsCapture.GameMemReader|Outdated version of the game
17:09:00.6409|INFO|AUCapture_WPF.MainWindow|No discord token set

```

**Describe the bug**
The Capture Client gets stuck on ```Waiting for Among Us``` and the logs think that the game is not up-to-date. I'm using ```v2020.12.5``` from the Microsoft Store, which is indeed up-to-date.

**To Reproduce**
1. Install game from Microsoft Store
2. Open Among Us Capture
3. Capture does not detect Among Us.

**Expected behavior**
Capture to detect Among Us

**Additional context**
I tested all of the versions of the Capture going back to ```3.1.1``` (when Microsoft Store support was added) and none of them work.
I've tried reinstalling Among Us.

**Comment by IDON-TEXIST** [comment]
I'm pretty sure the capture shouldn't be checking the gameassembly.dll hash for the microsoft store version in the first place, it should be detecting that it's the microsoft store version and just using those. Try running the capture as admin? Maybe it can't tell you're using microsoft store version for some reason.

**Comment by CarbonNeuron** [comment]
We do, but we expect it to fail. Because all our versions of microsoft store don't allow you to read the gameassembly. I will push a fix for this
