### ISSUE TITLE
Windows Defender labels the latest auto-update as a PUA

### ISSUE THREAD

**Issue by rorosaurus** [automuteus/amonguscapture#154]
**Describe the bug**
Windows Defender labels the latest auto-update as a PUA

**Screenshots**
![image](https://user-images.githubusercontent.com/908662/107841452-de1a6000-6d6f-11eb-866d-227be8d87db5.png)

MD5 hash of AmongUsCapture.exe:
7857fa5057e51a2f27db8b7622ed13de

**Comment by CarbonNeuron** [comment]
There is not much we can do besides say that if you think it is a virus, look at the code or build it yourself

**Comment by Wolfhound905** [comment]
I can not reproduce this.

**Comment by kurokobo** [comment]
F.Y.I. nothing detected by 69 different engines.
https://www.virustotal.com/gui/file/05e99c3437690f44e8b7ea43e1e8b74c818ddd35dc42d1273c72895185b90fb5/detection
