### ISSUE TITLE
Need new Offsets

### ISSUE THREAD

**Issue by emre1702** [automuteus/amonguscapture#162]
**Upload logs**
Not needed

**Describe the bug**
Among Us had 3-4 updates in Steam.
The offsets are now wrong.

I wanted to find out how to do it once and worked a bit with CheatEngine etc.
Some data I've found out. Some can be wrong, but maybe testing these is faster than trying to find them out :
Gamehash: 31E1F0C1D7370071F96514B8A76DE72FF0EE130F870A1BC157D63E0FBDA979D1
AmongUsClientOffset: 0x2C6C278
GameDataOffset: 0x2C6C07C
MeetingHudOffset: 0x2C6B78C
ServerManagerOffset: 0x2C63404
MeetingHudPtr: [0x2C6B78C,0x5c,0x0]
GameStateOffsets: [0x2C6C278,0x5c,0x0,0x6c]
AllPlayerPtrOffsets: [0x2C6C07C,0x5c,0x0,0x24]

Has been pretty hard to find the others as some have other names, some have more offsets etc.

**To Reproduce**
1. Use AmongUsCapture, won't work

**Expected behavior**
Correct Offsets, client should work

**Additional context**
Game had 3-4 updates some hours ago in Steam.

**Comment by CarbonNeuron** [comment]
Fixed in commit 8371c778c4b8ebb2f36b1580db96fff3fc6b8b13 and released in 3.2.0.
