### ISSUE TITLE
No Epic Launcher support with new update

### ISSUE THREAD

**Issue by NTullio8** [automuteus/amonguscapture#176]
Since the new AU/AUCapture updates, the capture does not recognize when an AU lobby starts on Epic version. Steam version works fine.

**Comment by CarbonNeuron** [comment]
Probably because of enum changes. 
@varedz

**Comment by varedz** [comment]
No, I'll wait a couple days to do Epic, Microsoft, and Itch. Just incase they decide to push out another couple updates.

**Comment by mtaku3** [comment]
@NTullio8 
Updated by now and you can play with newest Epic's Among Us v2021.4.1e 👍
