### ISSUE TITLE
The Other Roles Colors

### ISSUE THREAD

**Issue by Frozen-byte** [automuteus/amonguscapture#194]
**Is your feature request related to a problem? Please describe.**
Players love the new colors from https://github.com/Eisbison/TheOtherRoles#colors

**Describe the solution you'd like**
I guess not many players play with additional colors.  
So an optional parameter to trigger more colors?   
`.au new -modded`

**Comment by CarbonNeuron** [comment]
This would need server support aswell on  
https://github.com/denverquane/automuteus

**Comment by Frozen-byte** [comment]
Should I create a duplicate there?
