### ISSUE TITLE
All of the images are broken in the project's repo

### ISSUE THREAD

**Issue by hax4dazy** [automuteus/amonguscapture#410]
Every single image is missing from the project's repo. Isn't a huge issue but for people checking out the FAQ it is missing the example of what the error is supposed to look like.

**Comment by denverquane** [comment]
@Wolfhound905 this is why you don't use Discord as a CDN ;)

**Comment by denverquane** [comment]
No kidding, if only there was [another repo of ours](https://github.com/automuteus/automuteus/tree/master/assets) that had a convenient folder structure to emulate, too 😄

**Comment by kurokobo** [comment]
![image](https://github.com/user-attachments/assets/9efffc77-a45c-4a42-9a94-717468fc474e)

![image](https://github.com/user-attachments/assets/9fe3966b-b8be-4693-9b9f-45dcbae06fff)

![image](https://github.com/user-attachments/assets/7e5e1be7-7721-46fd-8195-3e97e75ede10)

**Comment by kurokobo** [comment]
@hax4dazy 
Good catch, thanks!
Luckily, the images stored in the old web archive.
